services:
  cassandra-local:
    image: cassandra:3.11
    container_name: keyspaces-dev
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  valkey-local:
    image: valkey/valkey:8
    container_name: valkey-dev
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  cassandra_data:
  valkey_data: